=== clayne/esp.json/schema/fields/struct.schema.json
{
  "$id": "esp.json/fields/struct.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Struct",
  "type": "object",
  "required": ["type", "elements"],
  "properties": {
    "type": {
      "constant": "struct"
    },
    "name": {
      "$ref": "../shared/name.schema.json"
    },
    "elements": {
      "type": "array",
      "items": {
        "$ref": "../field.schema.json"
      }
    },
    "sortKey": {
      "$ref": "../shared/sortKey.schema.json"
    }
  }
}

=== clayne/esp.json/data/SSE/ColorInterpolator.json
{
    "name": "Data",
    "type": "struct",
    "elements": [
        {
            "name": "Time",
            "type": "float"
        },
        {
            "name": "Red",
            "type": "float",
            "required": true
        },
        {
            "name": "Green",
            "type": "float",
            "required": true
        },
        {
            "name": "Blue",
            "type": "float",
            "required": true
        },
        {
            "name": "Alpha",
            "type": "float",
            "required": true
        }
    ],
    "sortKey": [
        0
    ]
}
