=== clayne/esp.json/schema/members/memberStruct.schema.json
{
  "$id": "esp.json/members/memberStruct.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Member Struct",
  "type": "object",
  "required": ["type", "members"],
  "properties": {
    "name": {
      "$ref": "../shared/name.schema.json"
    },
    "type": {
      "constant": "memberStruct"
    },
    "members": {
      "type": "array",
      "items": {
        "$ref": "../member.schema.json"
      }
    },
    "sortKey": {
      "$ref": "../shared/sortKey.schema.json"
    }
  }
}

=== clayne/esp.json/data/SSE/CSDT.json
{
    "name": "Sound Type",
    "type": "memberStruct",
    "members": [
        {
            "signature": "CSDT",
            "name": "Type",
            "type": "uint32",
            "format": {
                "type": "enum",
                "options": {
                    "0": "Left Foot",
                    "1": "Right Foot",
                    "2": "Left Back Foot",
                    "3": "Right Back Foot",
                    "4": "Idle",
                    "5": "Aware",
                    "6": "Attack",
                    "7": "Hit",
                    "8": "Death",
                    "9": "Weapon",
                    "10": "Movement Loop",
                    "11": "Conscious Loop",
                    "12": "Auxiliary 1",
                    "13": "Auxiliary 2",
                    "14": "Auxiliary 3",
                    "15": "Auxiliary 4",
                    "16": "Auxiliary 5",
                    "17": "Auxiliary 6",
                    "18": "Auxiliary 7",
                    "19": "Auxiliary 8",
                    "20": "Auxiliary 8",
                    "21": "Jump",
                    "22": "PlayRandom/Loop"
                }
            }
        },
        {
            "name": "Sounds",
            "type": "memberArray",
            "sorted": true,
            "required": true,
            "member": {
                "name": "Sound",
                "type": "memberStruct",
                "members": [
                    {
                        "signature": "CSDI",
                        "name": "Sound",
                        "type": "formId",
                        "required": true,
                        "signatures": [
                            "SNDR",
                            "NULL"
                        ]
                    },
                    {
                        "signature": "CSDC",
                        "name": "Sound Chance",
                        "type": "uint8",
                        "required": true
                    }
                ],
                "sortKey": [
                    0
                ]
            }
        }
    ],
    "sortKey": [
        0
    ]
}

=== clayne/esp.json/data/SSE/HeadPart.json
{
    "name": "Head Part",
    "type": "memberStruct",
    "members": [
        {
            "signature": "INDX",
            "name": "Head Part Number",
            "type": "uint32"
        },
        {
            "signature": "HEAD",
            "name": "Head",
            "type": "formId",
            "signatures": [
                "HDPT",
                "NULL"
            ]
        }
    ],
    "sortKey": [
        0
    ]
}

=== clayne/esp.json/data/FO4/CNTO.json
{
    "name": "Item",
    "type": "memberStruct",
    "members": [
        {
            "signature": "CNTO",
            "name": "Item",
            "type": "struct",
            "elements": [
                {
                    "name": "Item",
                    "type": "formId",
                    "signatures": {
                        "id": "sigBaseObjects"
                    }
                },
                {
                    "name": "Count",
                    "type": "int32"
                }
            ],
            "sortKey": [
                0
            ]
        },
        {
            "id": "COED"
        }
    ],
    "sortKey": [
        0
    ]
}

=== clayne/esp.json/data/TES4/SCITOBME.json
{
    "name": "Script effect",
    "type": "memberStruct",
    "members": [
        {
            "signature": "SCIT",
            "name": "Script effect data",
            "type": "struct",
            "required": true,
            "elements": [
                {
                    "name": "Script effect",
                    "type": "formId",
                    "signatures": [
                        "NULL",
                        "SCPT"
                    ]
                },
                {
                    "name": "Magic school",
                    "type": "uint32",
                    "format": {
                        "id": "MagicSchoolEnum"
                    }
                },
                {
                    "name": "Visual Effect Code",
                    "type": "mgefCode",
                    "size": 4
                },
                {
                    "name": "Flags",
                    "type": "uint8",
                    "format": {
                        "type": "flags",
                        "flags": {
                            "0": "Hostile"
                        }
                    }
                },
                {
                    "name": "Unused",
                    "type": "bytes",
                    "size": 3
                }
            ],
            "sortKey": [
                0
            ]
        },
        {
            "id": "FULL",
            "required": true
        }
    ],
    "sortKey": [
        0
    ]
}
