=== clayne/esp.json/schema/record.schema.json
{
  "$id": "esp.json/record.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of an esp.json record definition.",
  "type": "object",
  "required": ["signature", "type", "name", "def"],
  "properties": {
    "signature": {
      "$ref": "shared/signature.schema.json"
    },
    "type": {
      "const": "record"
    },
    "name": {
      "type": "string"
    },
    "def": {
      "oneOf": [{
        "$ref": "shared/def.schema.json"
      }, {
        "type": "object",
        "required": ["members"],
        "properties": {
          "flags": {
            "oneOf": [
              {
                "$ref": "format/flags.schema.json"
              },
              {
                "$ref": "format/formatUnion.schema.json"
              }
            ]
          },
          "members": {
            "type": "array",
            "items": {
              "$ref": "member.schema.json"
            }
          }
        }
      }]
    }
  }
}

=== clayne/esp.json/data/TES5/HAZD.json
{
    "signature": "HAZD",
    "type": "record",
    "name": "Hazard",
    "def": {
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "FULL"
            },
            {
                "def": "MODL"
            },
            {
                "signature": "MNAM",
                "type": "subrecord",
                "def": {
                    "name": "Image Space Modifier",
                    "type": "formId",
                    "signatures": [
                        "IMAD",
                        "NULL"
                    ]
                }
            },
            {
                "signature": "DATA",
                "type": "subrecord",
                "def": {
                    "name": "Data",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "Limit",
                            "type": "uint32"
                        },
                        {
                            "name": "Radius",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Lifetime",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Image Space Radius",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Target Interval",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Flags",
                            "type": "uint32",
                            "format": {
                                "0": "Affects Player Only",
                                "1": "Inherit Duration from Spawn Spell",
                                "2": "Align to Impact Normal",
                                "3": "Inherit Radius from Spawn Spell",
                                "4": "Drop to Ground"
                            }
                        },
                        {
                            "name": "Spell",
                            "type": "formId",
                            "signatures": [
                                "SPEL",
                                "ENCH",
                                "NULL"
                            ]
                        },
                        {
                            "name": "Light",
                            "type": "formId",
                            "signatures": [
                                "LIGH",
                                "NULL"
                            ]
                        },
                        {
                            "name": "Impact Data Set",
                            "type": "formId",
                            "signatures": [
                                "IPDS",
                                "NULL"
                            ]
                        },
                        {
                            "name": "Sound",
                            "type": "formId",
                            "signatures": [
                                "SNDR",
                                "NULL"
                            ]
                        }
                    ]
                }
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/DOOR.json
{
    "signature": "DOOR",
    "type": "record",
    "name": "Door",
    "def": {
        "flags": {
            "type": "flags",
            "flags": {
                "12": "Ignored",
                "15": "Has Distant LOD",
                "16": "Random Anim Start",
                "23": "Is Marker"
            }
        },
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "VMAD"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "FULL"
            },
            {
                "def": "MODL"
            },
            {
                "def": "DEST"
            },
            {
                "signature": "SNAM",
                "type": "subrecord",
                "def": {
                    "name": "Sound - Open",
                    "type": "formId",
                    "signatures": [
                        "SNDR"
                    ]
                }
            },
            {
                "signature": "ANAM",
                "type": "subrecord",
                "def": {
                    "name": "Sound - Close",
                    "type": "formId",
                    "signatures": [
                        "SNDR"
                    ]
                }
            },
            {
                "signature": "BNAM",
                "type": "subrecord",
                "def": {
                    "name": "Sound - Loop",
                    "type": "formId",
                    "signatures": [
                        "SNDR"
                    ]
                }
            },
            {
                "signature": "FNAM",
                "type": "subrecord",
                "def": {
                    "name": "Flags",
                    "type": "uint8",
                    "format": {
                        "type": "flags",
                        "flags": {
                            "0": "",
                            "1": "Automatic",
                            "2": "Hidden",
                            "3": "Minimal Use",
                            "4": "Sliding",
                            "5": "Do Not Open in Combat Search"
                        }
                    }
                }
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/SHOU.json
{
    "signature": "SHOU",
    "type": "record",
    "name": "Shout",
    "def": {
        "flags": {
            "type": "flags",
            "flags": {
                "7": "Treat spells as powers",
                "12": "Ignored"
            }
        },
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "FULL"
            },
            {
                "def": "MDOB"
            },
            {
                "def": "DESC"
            },
            {
                "name": "Words of Power",
                "type": "subrecordArray",
                "subrecord": {
                    "signature": "SNAM",
                    "type": "subrecord",
                    "def": {
                        "name": "",
                        "type": "struct",
                        "fields": [
                            {
                                "name": "Word",
                                "type": "formId",
                                "signatures": [
                                    "WOOP",
                                    "NULL"
                                ]
                            },
                            {
                                "name": "Spell",
                                "type": "formId",
                                "signatures": [
                                    "SPEL",
                                    "NULL"
                                ]
                            },
                            {
                                "name": "Recovery Time",
                                "type": "float"
                            }
                        ]
                    }
                }
            }
        ]
    }
}
