=== clayne/esp.json/schema/record.schema.json
{
  "$id": "esp.json/record.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of an esp.json record definition.",
  "type": "object",
  "required": ["signature", "type", "name", "def"],
  "properties": {
    "signature": {
      "$ref": "shared/signature.schema.json"
    },
    "type": {
      "const": "record"
    },
    "name": {
      "type": "string"
    },
    "def": {
      "oneOf": [{
        "$ref": "shared/def.schema.json"
      }, {
        "type": "object",
        "required": ["members"],
        "properties": {
          "flags": {
            "oneOf": [
              {
                "$ref": "format/flags.schema.json"
              },
              {
                "$ref": "format/formatUnion.schema.json"
              }
            ]
          },
          "members": {
            "type": "array",
            "items": {
              "$ref": "member.schema.json"
            }
          }
        }
      }]
    }
  }
}

=== clayne/esp.json/data/TES5/SNDR.json
{
    "signature": "SNDR",
    "type": "record",
    "name": "Sound Descriptor",
    "def": {
        "members": [
            {
                "def": "EDID"
            },
            {
                "signature": "CNAM",
                "type": "subrecord",
                "field": {
                    "name": "Unknown",
                    "type": "bytes"
                }
            },
            {
                "signature": "GNAM",
                "type": "subrecord",
                "field": {
                    "name": "Category",
                    "type": "formId"
                }
            },
            {
                "signature": "SNAM",
                "type": "subrecord",
                "field": {
                    "name": "Alternate Sound For",
                    "type": "formId",
                    "signatures": [
                        "SNDR",
                        "NULL"
                    ]
                }
            },
            {
                "name": "Sounds",
                "type": "memberArray",
                "member": {
                    "name": "Sound Files",
                    "type": "memberStruct",
                    "members": [
                        {
                            "signature": "ANAM",
                            "type": "subrecord",
                            "field": {
                                "name": "File Name",
                                "type": "string"
                            }
                        }
                    ]
                }
            },
            {
                "signature": "ONAM",
                "type": "subrecord",
                "field": {
                    "name": "Output Model",
                    "type": "formId",
                    "signatures": [
                        "SOPM",
                        "NULL"
                    ]
                }
            },
            {
                "signature": "FNAM",
                "type": "subrecord",
                "field": {
                    "name": "String",
                    "type": "string",
                    "localized": true
                }
            },
            {
                "def": "CTDAs"
            },
            {
                "signature": "LNAM",
                "type": "subrecord",
                "field": {
                    "name": "Values",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "Unknown",
                            "type": "bytes",
                            "size": 1
                        },
                        {
                            "name": "Looping",
                            "type": "uint8",
                            "format": {
                                "type": "enum",
                                "options": {
                                    "0": "None",
                                    "8": "Loop",
                                    "16": "Envelope Fast",
                                    "32": "Envelope Slow"
                                }
                            }
                        },
                        {
                            "name": "Unknown",
                            "type": "bytes",
                            "size": 1
                        },
                        {
                            "name": "Rumble Send Value = (Small / 7) + ((Big / 7) * 16)",
                            "type": "uint8"
                        }
                    ]
                }
            },
            {
                "signature": "BNAM",
                "type": "subrecord",
                "field": {
                    "name": "Values",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "% Frequency Shift",
                            "type": "int8"
                        },
                        {
                            "name": "% Frequency Variance",
                            "type": "int8"
                        },
                        {
                            "name": "Priority",
                            "type": "uint8"
                        },
                        {
                            "name": "db Variance",
                            "type": "uint8"
                        },
                        {
                            "name": "Static Attenuation (db)",
                            "type": "uint16",
                            "format": {
                                "type": "divide",
                                "value": 100
                            }
                        }
                    ]
                }
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/MSTT.json
{
    "signature": "MSTT",
    "type": "record",
    "name": "Moveable Static",
    "def": {
        "flags": {
            "8": "Must Update Anims",
            "9": "Hidden From Local Map",
            "15": "Has Distant LOD",
            "16": "Random Anim Start",
            "19": "Has Currents",
            "25": "Obstacle",
            "26": "NavMesh Generation - Filter",
            "27": "NavMesh Generation - Bounding Box",
            "30": "NavMesh Generation - Ground"
        },
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "FULL"
            },
            {
                "def": "MODL"
            },
            {
                "def": "DEST"
            },
            {
                "signature": "DATA",
                "type": "subrecord",
                "def": {
                    "name": "Flags",
                    "type": "uint8",
                    "format": {
                        "0": "On Local Map",
                        "1": "Unknown 1",
                        "2": "Unknown 2"
                    }
                }
            },
            {
                "signature": "SNAM",
                "type": "subrecord",
                "def": {
                    "name": "Looping Sound",
                    "type": "formId",
                    "signatures": [
                        "SNDR"
                    ]
                }
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/TREE.json
{
    "signature": "TREE",
    "type": "record",
    "name": "Tree",
    "def": {
        "flags": {
            "type": "flags",
            "flags": {
                "15": "Has Distant LOD"
            }
        },
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "VMAD"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "MODL"
            },
            {
                "signature": "PFIG",
                "type": "subrecord",
                "def": {
                    "name": "Ingredient",
                    "type": "formId",
                    "signatures": [
                        "INGR",
                        "ALCH",
                        "MISC",
                        "LVLI",
                        "NULL"
                    ]
                }
            },
            {
                "signature": "SNAM",
                "type": "subrecord",
                "def": {
                    "name": "Harvest Sound",
                    "type": "formId",
                    "signatures": [
                        "SNDR",
                        "NULL"
                    ]
                }
            },
            {
                "signature": "PFPC",
                "type": "subrecord",
                "def": {
                    "name": "Ingredient Production",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "Spring",
                            "type": "uint8"
                        },
                        {
                            "name": "Summer",
                            "type": "uint8"
                        },
                        {
                            "name": "Fall",
                            "type": "uint8"
                        },
                        {
                            "name": "Winter",
                            "type": "uint8"
                        }
                    ]
                }
            },
            {
                "def": "FULL"
            },
            {
                "signature": "CNAM",
                "type": "subrecord",
                "def": {
                    "name": "Tree Data",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "Trunk Flexibility",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Branch Flexibility",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Unknown",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Leaf Amplitude",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Leaf Frequency",
                            "type": "float",
                            "formatter": ""
                        }
                    ]
                },
                "required": true
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/WATR.json
{
    "signature": "WATR",
    "type": "record",
    "name": "Water",
    "def": {
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "FULL"
            },
            {
                "name": "Unused",
                "type": "subrecordArray",
                "subrecord": {
                    "signature": "NNAM",
                    "type": "subrecord",
                    "def": {
                        "name": "Noise Map",
                        "type": "string"
                    },
                    "required": true
                }
            },
            {
                "signature": "ANAM",
                "type": "subrecord",
                "def": {
                    "name": "Opacity",
                    "type": "uint8"
                }
            },
            {
                "signature": "FNAM",
                "type": "subrecord",
                "def": {
                    "name": "Flags",
                    "type": "uint8",
                    "format": {
                        "0": "Causes Damage",
                        "1": "Unknown 1",
                        "2": "Unknown 2",
                        "5": "Unknown 5",
                        "6": "Unknown 6",
                        "7": "Unknown 7"
                    }
                }
            },
            {
                "signature": "MNAM",
                "type": "subrecord",
                "def": {
                    "name": "Unused",
                    "type": "bytes",
                    "size": 0
                }
            },
            {
                "signature": "TNAM",
                "type": "subrecord",
                "def": {
                    "name": "Material",
                    "type": "formId",
                    "signatures": [
                        "MATT"
                    ]
                }
            },
            {
                "signature": "SNAM",
                "type": "subrecord",
                "def": {
                    "name": "Open Sound",
                    "type": "formId",
                    "signatures": [
                        "SNDR",
                        "NULL"
                    ]
                }
            },
            {
                "signature": "XNAM",
                "type": "subrecord",
                "def": {
                    "name": "Spell",
                    "type": "formId",
                    "signatures": [
                        "SPEL"
                    ]
                }
            },
            {
                "signature": "INAM",
                "type": "subrecord",
                "def": {
                    "name": "Image Space",
                    "type": "formId",
                    "signatures": [
                        "IMGS"
                    ]
                }
            },
            {
                "signature": "DATA",
                "type": "subrecord",
                "def": {
                    "name": "Damage Per Second",
                    "type": "uint16"
                }
            },
            null,
            {
                "signature": "GNAM",
                "type": "subrecord",
                "def": {
                    "name": "Unused",
                    "type": "bytes",
                    "size": 0
                }
            },
            {
                "signature": "NAM0",
                "type": "subrecord",
                "def": {
                    "name": "Linear Velocity",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "X",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Y",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Z",
                            "type": "float",
                            "formatter": ""
                        }
                    ]
                },
                "required": true
            },
            {
                "signature": "NAM1",
                "type": "subrecord",
                "def": {
                    "name": "Angular Velocity",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "X",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Y",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Z",
                            "type": "float",
                            "formatter": ""
                        }
                    ]
                },
                "required": true
            },
            {
                "signature": "NAM2",
                "type": "subrecord",
                "def": {
                    "name": "Noise Layer One - Noise Texture",
                    "type": "string"
                },
                "required": true
            },
            {
                "signature": "NAM3",
                "type": "subrecord",
                "def": {
                    "name": "Noise Layer Two - Noise Texture",
                    "type": "string"
                },
                "required": true
            },
            {
                "signature": "NAM4",
                "type": "subrecord",
                "def": {
                    "name": "Noise Layer Three - Noise Texture",
                    "type": "string"
                },
                "required": true
            },
            {
                "signature": "NAM5",
                "type": "subrecord",
                "def": {
                    "name": "Flow Normals - Noise Texture",
                    "type": "string"
                },
                "required": true
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/SCOL.json
{
    "signature": "SCOL",
    "type": "record",
    "name": "Static Collection",
    "def": {
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "MODL",
                "required": true
            },
            {
                "name": "Parts",
                "type": "structArray",
                "entryName": {
                    "name": "Part",
                    "type": "multiStruct",
                    "subrecords": [
                        {
                            "signature": "ONAM",
                            "type": "subrecord",
                            "def": {
                                "name": "Static",
                                "type": "formId",
                                "signatures": [
                                    "STAT"
                                ]
                            }
                        },
                        {
                            "signature": "DATA",
                            "type": "subrecord",
                            "def": {
                                "name": "Placements",
                                "entryDef": {
                                    "name": "Placement",
                                    "type": "struct",
                                    "fields": [
                                        {
                                            "name": "Position",
                                            "type": "struct",
                                            "fields": [
                                                {
                                                    "name": "X",
                                                    "type": "float"
                                                },
                                                {
                                                    "name": "Y",
                                                    "type": "float"
                                                },
                                                {
                                                    "name": "Z",
                                                    "type": "float"
                                                }
                                            ]
                                        },
                                        {
                                            "name": "Rotation",
                                            "type": "struct",
                                            "fields": [
                                                {
                                                    "name": "X",
                                                    "type": "float",
                                                    "required": true
                                                },
                                                {
                                                    "name": "Y",
                                                    "type": "float",
                                                    "required": true
                                                },
                                                {
                                                    "name": "Z",
                                                    "type": "float",
                                                    "required": true
                                                }
                                            ]
                                        },
                                        {
                                            "name": "Scale",
                                            "type": "float"
                                        }
                                    ]
                                },
                                "type": "array",
                                "size": 0
                            }
                        }
                    ]
                },
                "required": true
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/PLYR.json
{
    "signature": "PLYR",
    "type": "record",
    "name": "Player Reference",
    "def": {
        "members": [
            {
                "def": "EDID"
            },
            {
                "signature": "PLYR",
                "type": "subrecord",
                "field": {
                    "name": "Player",
                    "type": "formId"
                },
                "required": true,
                "defaultNativeValue": 7
            }
        ]
    }
}

=== clayne/esp.json/data/TES5/ALCH.json
{
    "signature": "ALCH",
    "type": "record",
    "name": "Ingestible",
    "def": {
        "flags": {
            "type": "flags",
            "flags": {
                "29": "Medicine"
            }
        },
        "members": [
            {
                "def": "EDID"
            },
            {
                "def": "OBND",
                "required": true
            },
            {
                "def": "FULL"
            },
            {
                "def": "KSIZ"
            },
            {
                "def": "KWDAs"
            },
            {
                "def": "DESC"
            },
            {
                "def": "MODL"
            },
            {
                "def": "DEST"
            },
            {
                "def": "ICON"
            },
            {
                "def": "YNAM"
            },
            {
                "def": "ZNAM"
            },
            {
                "def": "ETYP"
            },
            {
                "signature": "DATA",
                "type": "subrecord",
                "def": {
                    "name": "Weight",
                    "type": "float",
                    "formatter": ""
                },
                "required": true
            },
            {
                "signature": "ENIT",
                "type": "subrecord",
                "def": {
                    "name": "Effect Data",
                    "type": "struct",
                    "fields": [
                        {
                            "name": "Value",
                            "type": "int32"
                        },
                        {
                            "name": "Flags",
                            "type": "uint32",
                            "format": {
                                "type": "flags",
                                "flags": {
                                    "0": "No Auto-Calc",
                                    "1": "Food Item",
                                    "2": "Unknown 3",
                                    "3": "Unknown 4",
                                    "4": "Unknown 5",
                                    "5": "Unknown 6",
                                    "6": "Unknown 7",
                                    "7": "Unknown 8",
                                    "8": "Unknown 9",
                                    "9": "Unknown 10",
                                    "10": "Unknown 11",
                                    "11": "Unknown 12",
                                    "12": "Unknown 13",
                                    "13": "Unknown 14",
                                    "14": "Unknown 15",
                                    "15": "Unknown 16",
                                    "16": "Medicine",
                                    "17": "Poison"
                                }
                            }
                        },
                        {
                            "name": "Addiction",
                            "type": "formId"
                        },
                        {
                            "name": "Addiction Chance",
                            "type": "float",
                            "formatter": ""
                        },
                        {
                            "name": "Sound - Consume",
                            "type": "formId",
                            "signatures": [
                                "SNDR",
                                "NULL"
                            ]
                        }
                    ]
                },
                "required": true
            },
            {
                "def": "Effects",
                "required": true
            }
        ]
    }
}
